export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';
export const ACCOUNT_DELETED = 'ACCOUNT_DELETED';

// CHANNEL
export const CHANNELS_LOADED = 'CHANNELS_LOADED';
export const CHANNEL_LOADED = 'CHANNEL_LOADED';

// CHANNEL
export const CATEGORIES_LOADED = 'CATEGORIES_LOADED';
export const CATEGORY_LOADED = 'CATEGORY_LOADED';